---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudBD Ubuntu 18.04/bionic Template:
  This template creates and configures an EC2 instance using the VPC,
  S3 Bucket, IAM user and SSH key-pair from the remote template.'
Parameters:
  InstanceName:
    Description: The Ubuntu 18.04/bionic unique name of the instance
    Type: String
    MinLength: '1'
    MaxLength: '32'
    AllowedPattern: "[a-zA-Z][a-zA-Z_0-9-]*"
    ConstraintDescription: must start with an alphabetic character and contain only alphanumeric characters (case-sensitive) and hyphens. 32 chars max.
  RemoteName:
    Description: The remote name
    Type: String
    MinLength: '1'
    MaxLength: '32'
    AllowedPattern: "[a-zA-Z][a-zA-Z_0-9-]*"
    ConstraintDescription: must start with an alphabetic character and contain only alphanumeric characters (case-sensitive) and hyphens. 32 chars max.
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  CredentialsURL:
    Description: Presigned URL to credentials.json
    Type: String
    Default: ""
  RemoteConfURL:
    Description: Presigned URL to remotes.d conf file
    Type: String
    Default: ""
  InstanceType:
    Description: EC2 instance type
    Type: String
  AvailabilityZone:
    Description: The Availability Zone letter to create the EC2 instance
    Type: String
    MinLength: '1'
    MaxLength: '1'
    AllowedPattern: "[a-f]"
    ConstraintDescription: must be a single character in the range a-f
Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0a313d6098716f372
    us-east-2:
      HVM64: ami-0c55b159cbfafe1f0
    us-west-1:
      HVM64: ami-06397100adf427136
    us-west-2:
      HVM64: ami-005bdb005fb00e791
    ca-central-1:
      HVM64: ami-01b60a3259250381b
    eu-west-1:
      HVM64: ami-08d658f84a6d84a80
    eu-west-2:
      HVM64: ami-07dc734dc14746eab
    eu-west-3:
      HVM64: ami-03bca18cb3dc173c9
    eu-central-1:
      HVM64: ami-090f10efc254eaf55
    ap-northeast-1:
      HVM64: ami-0eb48a19a8d81e20b
    ap-northeast-2:
      HVM64: ami-078e96948945fc2c9
    ap-southeast-1:
      HVM64: ami-0dad20bd1b9c8c004
    ap-southeast-2:
      HVM64: ami-0b76c3b150c6b1423
    ap-south-1:
      HVM64: ami-007d5db58754fa284
    sa-east-1:
      HVM64: ami-09f4cd7c0b533b081
Resources:
  CloudBDBionicInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - Fn::ImportValue: !Sub 'cloudbd-resources-${RemoteName}-SecurityGroup'
        - Fn::ImportValue: !Sub 'cloudbd-resources-${RemoteName}-DefaultSecurityGroup'
      SubnetId:
        Fn::ImportValue: !Sub 'cloudbd-resources-${RemoteName}-subnet-${AvailabilityZone}'
      KeyName: !Ref KeyName
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - !Ref AWS::Region
        - HVM64
      Tags:
        -
          Key: Name
          Value: !Sub 'cloudbd-ec2-${InstanceName}'
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -x
            export DEBIAN_FRONTEND=noninteractive

            # The regional <region>.ec2.archive.ubuntu.com sources frequently
            # are not responsive or very very slow causing instances to time-out
            # so let's not use them.
            sed -i 's/http:.*\.ec2\.archive\.ubuntu\.com\/ubuntu\//mirror:\/\/mirrors\.ubuntu\.com\/mirrors\.txt/' /etc/apt/sources.list

            # upgrade packages and kernel
            apt-get -y update
            apt-get -y dist-upgrade

            # install cfn bootstrap package
            apt-get -y install python-pip
            pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

            # perform AWS::CloudFormation::Init tasks
            /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource CloudBDBionicInstance --configsets default --region ${AWS::Region}

            # reboot if needed and signal completion to cloudfront
            RET=$?
            if [ -e /var/run/reboot-required ]; then
              cat <<- EOF > /etc/cron.d/cfn-signal
            	SHELL=/bin/bash
            	PATH=/sbin:/bin:/usr/sbin:/usr/bin
            	MAILTO=root
            	HOME=/
            	@reboot root { /usr/local/bin/cfn-signal -e ${!RET} --stack ${AWS::StackName} --resource CloudBDBionicInstance --region ${AWS::Region}; rm /etc/cron.d/cfn-signal; } > /dev/null
            	EOF
              reboot
            else
              /usr/local/bin/cfn-signal -e ${!RET} --stack ${AWS::StackName} --resource CloudBDBionicInstance --region ${AWS::Region}
            fi
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
            - CfnHupInstall
            - RepoInstall
            - Install
        CfnHupInstall:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackName}
                region=${AWS::Region}
                interval=15
                verbose=true
              mode: "000400"
              owner: "root"
              group: "root"
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.CloudBDBionicInstance.Metadata
                action=/usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource CloudBDBionicInstance --configsets default --region ${AWS::Region}
                runas=root
              mode: "000400"
              owner: "root"
              group: "root"
            /etc/systemd/system/cfn-hup.service:
              content: !Sub |
                [Unit]
                Description=Cloud formation helper daemon

                [Service]
                ExecStart=/usr/local/bin/cfn-hup
                Restart=always
                Type=simple

                [Install]
                WantedBy=multi-user.target
          commands:
            01-install-cfn-hup:
              command: !Sub |
                set -xe
                systemctl enable cfn-hup.service
                systemctl start cfn-hup.service
        RepoInstall:
          files:
            /etc/apt/sources.list.d/cloudbd.list:
              source: https://repo.cloudbd.io/bionic/cloudbd.list
              mode: "000644"
              owner: "root"
              group: "root"
            /usr/share/keyrings/cloudbd-keyring.gpg:
              source: https://repo.cloudbd.io/cloudbd-keyring.gpg
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            01-apt-update:
              command: !Sub |
                set -xe
                apt-get -y update
        Install:
          files:
            /etc/sysctl.d/20-cloudbd.conf:
              content: !Sub |
                vm.dirty_background_bytes=2097152
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            01-packages:
              command: !Sub |
                set -xe
                apt-get -y install cbd-client
            02-remote-conf:
              command: !Sub
                - |
                  set -xe
                  ConfURL="${ConfURL}"
                  ConfFile="${ConfFile}"
                  if [ -n "${!ConfURL}" ] && [ ! -f ${!ConfFile} ]; then
                    umask 027;
                    curl -sSfo ${!ConfFile} ${!ConfURL}
                    chown root:cloudbd ${!ConfFile}
                  fi
                - ConfURL: !Ref RemoteConfURL
                  ConfFile: !Sub '/etc/cloudbd/remotes.d/${RemoteName}.conf'
            03-creds:
              command: !Sub
                - |
                  set -xe
                  ConfURL="${ConfURL}"
                  ConfFile="${ConfFile}"
                  if [ -n "${!ConfURL}" ] && [ ! -f ${!ConfFile} ]; then
                    umask 027;
                    curl -sSfo ${!ConfFile} ${!ConfURL}
                    chown root:cloudbd ${!ConfFile}
                  fi
                - ConfURL: !Ref CredentialsURL
                  ConfFile: /etc/cloudbd/credentials.json
            04-cloudbd-group:
              command: !Sub |
                set -xe
                usermod -a -G cloudbd ubuntu
            05-sysctls:
              command: !Sub |
                set -xe
                sysctl vm.dirty_background_bytes=2097152
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref CloudBDBionicInstance
  OperatingSystem:
    Description: Operating system name
    Value: 'bionic'
  RemoteName:
    Description: Remote name this instance was created in
    Value: !Ref RemoteName
