---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudBD Remote Resources Template:
  This template configures a CloudBD remote with an S3 bucket, VPC with S3
  endpoint and a IAM user with access to the bucket for testing CloudBD disks.'
Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  AvailabilityZones:
    Description: The comma delimited list of 6 availibilty zone names, or false
    Type: List<String>
    ConstraintDescription: must be a comma delimited list of 6 availibilty zone names, or false
Conditions:
  AvailabilityZoneA:
    !Not [!Equals [!Select [0, !Ref AvailabilityZones], false]]
  AvailabilityZoneB:
    !Not [!Equals [!Select [1, !Ref AvailabilityZones], false]]
  AvailabilityZoneC:
    !Not [!Equals [!Select [2, !Ref AvailabilityZones], false]]
  AvailabilityZoneD:
    !Not [!Equals [!Select [3, !Ref AvailabilityZones], false]]
  AvailabilityZoneE:
    !Not [!Equals [!Select [4, !Ref AvailabilityZones], false]]
  AvailabilityZoneF:
    !Not [!Equals [!Select [5, !Ref AvailabilityZones], false]]
Resources:
  CloudBDS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
  CloudBDTestUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: cloudbd-test-user-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:ListBucket
                Resource:
                  - Fn::GetAtt: [ "CloudBDS3Bucket", "Arn" ]
              - Effect: Allow
                Action:
                  - s3:HeadBucket
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - Fn::Join:
                    - ""
                    -
                      - Fn::GetAtt: [ "CloudBDS3Bucket", "Arn" ]
                      - "/cloudbd/*"
  CloudBDVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  CloudBDInternetGateway:
    Type: AWS::EC2::InternetGateway
  CloudBDGatewayAtachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref CloudBDVPC
      InternetGatewayId: !Ref CloudBDInternetGateway
  CloudBDRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CloudBDVPC
  CloudBDDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: CloudBDGatewayAtachment
    Properties:
      RouteTableId: !Ref CloudBDRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref CloudBDInternetGateway
  CloudBDSubnetA:
    Type: AWS::EC2::Subnet
    Condition: AvailabilityZoneA
    Properties:
      AvailabilityZone: !Select [0, !Ref AvailabilityZones]
      CidrBlock: 172.16.0.0/20
      MapPublicIpOnLaunch: true
      VpcId: !Ref CloudBDVPC
  CloudBDSubnetAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AvailabilityZoneA
    Properties:
      RouteTableId: !Ref CloudBDRouteTable
      SubnetId: !Ref CloudBDSubnetA
  CloudBDSubnetB:
    Type: AWS::EC2::Subnet
    Condition: AvailabilityZoneB
    Properties:
      AvailabilityZone: !Select [1, !Ref AvailabilityZones]
      CidrBlock: 172.16.80.0/20
      MapPublicIpOnLaunch: true
      VpcId: !Ref CloudBDVPC
  CloudBDSubnetBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AvailabilityZoneB
    Properties:
      RouteTableId: !Ref CloudBDRouteTable
      SubnetId: !Ref CloudBDSubnetB
  CloudBDSubnetC:
    Type: AWS::EC2::Subnet
    Condition: AvailabilityZoneC
    Properties:
      AvailabilityZone: !Select [2, !Ref AvailabilityZones]
      CidrBlock: 172.16.16.0/20
      MapPublicIpOnLaunch: true
      VpcId: !Ref CloudBDVPC
  CloudBDSubnetCAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AvailabilityZoneC
    Properties:
      RouteTableId: !Ref CloudBDRouteTable
      SubnetId: !Ref CloudBDSubnetC
  CloudBDSubnetD:
    Type: AWS::EC2::Subnet
    Condition: AvailabilityZoneD
    Properties:
      AvailabilityZone: !Select [3, !Ref AvailabilityZones]
      CidrBlock: 172.16.32.0/20
      MapPublicIpOnLaunch: true
      VpcId: !Ref CloudBDVPC
  CloudBDSubnetDAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AvailabilityZoneD
    Properties:
      RouteTableId: !Ref CloudBDRouteTable
      SubnetId: !Ref CloudBDSubnetD
  CloudBDSubnetE:
    Type: AWS::EC2::Subnet
    Condition: AvailabilityZoneE
    Properties:
      AvailabilityZone: !Select [4, !Ref AvailabilityZones]
      CidrBlock: 172.16.64.0/20
      MapPublicIpOnLaunch: true
      VpcId: !Ref CloudBDVPC
  CloudBDSubnetEAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AvailabilityZoneE
    Properties:
      RouteTableId: !Ref CloudBDRouteTable
      SubnetId: !Ref CloudBDSubnetE
  CloudBDSubnetF:
    Type: AWS::EC2::Subnet
    Condition: AvailabilityZoneF
    Properties:
      AvailabilityZone: !Select [5, !Ref AvailabilityZones]
      CidrBlock: 172.16.48.0/20
      MapPublicIpOnLaunch: true
      VpcId: !Ref CloudBDVPC
  CloudBDSubnetFAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: AvailabilityZoneF
    Properties:
      RouteTableId: !Ref CloudBDRouteTable
      SubnetId: !Ref CloudBDSubnetF
  CloudBDS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref CloudBDVPC
      RouteTableIds:
        - !Ref CloudBDRouteTable
      ServiceName:
        Fn::Join:
          - '.'
          -
            - com.amazonaws
            - !Ref AWS::Region
            - s3
  CloudBDSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref CloudBDVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref SSHLocation
Outputs:
  BucketName:
    Description: Name of the CloudBD test bucket
    Value: !Ref CloudBDS3Bucket
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", BucketName ] ]
  UserName:
    Description: Name of the CloudBD test user
    Value: !Ref CloudBDTestUser
  SecurityGroup:
    Description: CloudBD Security Group Ref
    Value: !Ref CloudBDSecurityGroup
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", SecurityGroup ] ]
  SubNetA:
    Description: CloudBD Subnet A Ref
    Value:
      !If [AvailabilityZoneA, !Ref CloudBDSubnetA, 'unconfigured' ]
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", subnet-a ] ]
  SubNetB:
    Description: CloudBD Subnet B Ref
    Value:
      !If [AvailabilityZoneB, !Ref CloudBDSubnetB, 'unconfigured' ]
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", subnet-b ] ]
  SubNetC:
    Description: CloudBD Subnet C Ref
    Value:
      !If [AvailabilityZoneC, !Ref CloudBDSubnetC, 'unconfigured' ]
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", subnet-c ] ]
  SubNetD:
    Description: CloudBD Subnet D Ref
    Value:
      !If [AvailabilityZoneD, !Ref CloudBDSubnetD, 'unconfigured' ]
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", subnet-d ] ]
  SubNetE:
    Description: CloudBD Subnet E Ref
    Value:
      !If [AvailabilityZoneE, !Ref CloudBDSubnetE, 'unconfigured' ]
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", subnet-e ] ]
  SubNetF:
    Description: CloudBD Subnet F Ref
    Value:
      !If [AvailabilityZoneF, !Ref CloudBDSubnetE, 'unconfigured' ]
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", subnet-f ] ]
